# Generated by Django 5.1.5 on 2025-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='_rating',
            field=models.IntegerField(db_column='rating_comments', default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='_rating',
            field=models.IntegerField(db_column='rating_post', default=0),
        ),
    ]
