# Generated by Django 5.1.5 on 2025-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename__rating_comment__rating_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='_rating_autor',
            new_name='rating_autor',
        ),
    ]
