# Generated by Django 5.1.5 on 2025-03-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
