# Generated by Django 5.1.5 on 2025-02-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename__rating_comments_comment_rating_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
